### ISSUE TITLE
SYSTEM_ADDRESS is wrong in /BOOT/Inc/btld.h#L34

### ISSUE THREAD

**Issue by dakhnod** [effenco/stm32-can-bootloader#9]
In https://github.com/effenco/stm32-can-bootloader/blob/master/BOOT/Inc/btld.h#L34, you define SYSMEM_ADDRESS  as 0x1FFF0000.
Judging by the [datasheet](https://www.st.com/resource/en/datasheet/stm32f373rc.pdf) page 48, the system memory starts at 0x1FFFD800.

Would you be kind enough to explain where that difference comes from? Should't SYSMEM_ADDRESS  be defined as 0x1FFFD800?

**Comment by Rotule666** [comment]
Hello sir, first of all Thanks for posting a clear question and include the reference with links, it make it so much easier to understand the question.

I think you are right that the SYSTEM_ADDRESS is wrong but because it is not used it has no effect. We will still keep this issue opened and address it later on.

**Comment by dakhnod** [comment]
I created [this](https://github.com/effenco/stm32-can-bootloader/pull/10) PR, could you accept it?
